### ISSUE TITLE
Add model publishing guidelines to Read the Docs

### ISSUE THREAD

**Issue by ascourtas** [DLHub-Argonne/dlhub_sdk#177]
_As a Publisher, I want to know the best practices for publishing a model to improve my understanding and reduce user error_
_As a Developer, we need to make that documentation readily available and usable_

# Assumptions
1. Guidelines are already written out in text here, and just need to be added to DLHub's Read the Docs:
https://docs.google.com/document/d/16iWyX01tyo6PTW2RG6AnL_myfCEaMww2x6NH8AVqpJ0/edit#

# Acceptance Criteria
1. Given they can access the documentation, a Publisher can easily find and use the Publishing Guidelines while publishing.
2. A Publisher using either Foundry or DLHub could easily access this information
3. Given the Publishing Guidelines, a Publisher will know how to troubleshoot their model, understand best publishing practices, and feels empowered to debug their own publication if it fails. 

# Tasks

- [ ] Review guidelines in Google Docs again 
- [ ] add the guidelines in Google Docs to DLHub Read the Docs with proper formatting and links
- [ ] link in Foundry GitBook documentation accordingly
